"use client";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  return (
    <html lang="es">
      <body className={`${inter.className}`}>
        <div className="bg">
          <div className="logo_content">
            Bienvenido a &nbsp;&nbsp;
            <img src="/assets/images/logo.png" width={200} />
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
